# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular Terms or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7a16ebdd7f5595aad712f2d43c66990c2ec4ce81702780ce8ab2fab4010c8b0fe1f50d16b5d80e5f3051b090cee85180802a3d74d03f4676fdb466d1090d824

test:
  secret_key_base: 18066e9a529bff0fb325bbed0395487bf66f5de5b910ec6836a50bc79d14ea6b72da9ebb3be76c9f370931964d6dfec390bf687a7afdb91a75c0575eddb81cea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
